insert into books (bookId, title, priceOld, price) values (1, 'exploit real-time e-commerce', '203.23', '43.37');
insert into books (bookId, title, priceOld, price) values (2, 'utilize real-time interfaces', '260.31', '35.96');
insert into books (bookId, title, priceOld, price) values (3, 'extend strategic e-services', '272.00', '151.04');
insert into books (bookId, title, priceOld, price) values (4, 'iterate integrated solutions', '271.58', '141.40');
insert into books (bookId, title, priceOld, price) values (5, 'cultivate magnetic e-commerce', '278.43', '54.44');
insert into books (bookId, title, priceOld, price) values (5, 'architect vertical ROI', '282.54', '102.61');
insert into books (bookId, title, priceOld, price) values (6, 'disintermediate extensible architectures', '295.38', '181.27');
insert into books (bookId, title, priceOld, price) values (7, 'extend leading-edge methodologies', '283.08', '97.96');
insert into books (bookId, title, priceOld, price) values (8, 'integrate one-to-one systems', '258.51', '52.25');
insert into books (bookId, title, priceOld, price) values (9, 'revolutionize 24/7 infrastructures', '260.79', '33.69');
insert into books (bookId, title, priceOld, price) values (10, 'enhance innovative e-services', '256.54', '160.98');
insert into books (bookId, title, priceOld, price) values (11, 'maximize 24/365 e-tailers', '262.07', '34.06');
insert into books (bookId, title, priceOld, price) values (12, 'scale integrated architectures', ' 257.66', '32.97');
insert into books (bookId, title, priceOld, price) values (13, 'e-enable frictionless web services', '288.19', '90.52');
insert into books (bookId, title, priceOld, price) values (14, 'strategize B2B channels', '232.27', '44.83');
insert into books (bookId, title, priceOld, price) values (15, 'syndicate compelling deliverables', '287.45', '101.89');
insert into books (bookId, title, priceOld, price) values (16, 'utilize bleeding-edge users', '281.37', '146.21');
insert into books (bookId, title, priceOld, price) values (17, 'cultivate 24/365 networks', '270.99', '184.76');
insert into books (bookId, title, priceOld, price) values (18, 'embrace plug-and-play platforms', '278.36', '77.71');
insert into books (bookId, title, priceOld, price) values (19, 'target innovative paradigms', '298.94', '130.01');
insert into books (bookId, title, priceOld, price) values (20, 'generate open-source e-business', '276.57', '113.25');
insert into books (bookId, title, priceOld, price) values (21, 'implement user-centric e-markets', '254.70', '115.31');
insert into books (bookId, title, priceOld, price) values (22, 'utilize magnetic supply-chains', '279.70', '77.86');
insert into books (bookId, title, priceOld, price) values (23,  'e-enable dot-com supply-chains', '297.83', '110.15');
insert into books (bookId, title, priceOld, price) values (24, 'facilitate efficient eyeballs', '232.30', '131.48');


insert into authors (author, bookId) values ('Drucie Goodbourn',    1);
insert into authors (author, bookId) values ('Marcia Aggiss',       2);
insert into authors (author, bookId) values ('Giovanni Bigg',       3);
insert into authors (author, bookId) values ('Duffie Eynon',        4);
insert into authors (author, bookId) values ('Anselma McKennan',    5);
insert into authors (author, bookId) values ('Gert Kira',           5);
insert into authors (author, bookId) values ('Clerc Djakovic',      6);
insert into authors (author, bookId) values ('Stacee Elsy',         7);
insert into authors (author, bookId) values ('Dorotea Bonhill',     8);
insert into authors (author, bookId) values ('Minni Bunney',        9);
insert into authors (author, bookId) values ('Berty Gandley',       10);
insert into authors (author, bookId) values ('Raynard Tesdale',     11);
insert into authors (author, bookId) values ('Joanna Hutfield',     12);
insert into authors (author, bookId) values ('Dannie Glidder',      13);
insert into authors (author, bookId) values ('Timmie Adshede',      14);
insert into authors (author, bookId) values ('Fernando Neads',      15);
insert into authors (author, bookId) values ('Teddy Guilliland',    16);
insert into authors (author, bookId) values ('Paloma Grebert',      17);
insert into authors (author, bookId) values ('Kristos Usher',       18);
insert into authors (author, bookId) values ('Darcey Rohmer',       19);
insert into authors (author, bookId) values ('Cristie Isacsson',    20);
insert into authors (author, bookId) values ('Lindsay Coutthart',   21);
insert into authors (author, bookId) values ('Helyn Schneidar',     22);
insert into authors (author, bookId) values ('Bette-ann Askem',     23);
insert into authors (author, bookId) values ('Dom Robuchon',        24);